version: '3'
services:
  database:
    image: mysql:${MYSQL_VERSION:-8.0}-oracle
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
    volumes:
      - db-data:/var/lib/mysql:rw

  app:
    image: 2163b3ac5c1b5844fb5bf7976c1b0bb82104b5242294745cbfc48ccd3ecc6b72  
    ports:
      - "8081:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-symfony}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
   

volumes:
  db-data:


  app-network:
    driver: bridge

